name: github pages

on:
  push:
    branches:
    # 你的hugo源码分支
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      # 如果使用了git submodules
      #with:
        #submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.74.3'
        extended: true

    - name: Build
      run: hugo --gc --minify --cleanDestinationDir

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: public
      with:
        emptyCommits: false
      
    - name: Install Node.js
      uses: actions/setup-node@v1
      with: 
        node-version: '14.x'

    - name: Install automic-algolia
      run: | 
        npm install atomic-algolia
        npm run algolia
      env:
        ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
        ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
        ALGOLIA_INDEX_NAME: "index"
        ALGOLIA_INDEX_FILE: "public/index.json"
        

